In [2]:
import numpy as np

data = np.load("data/train_uw.npy")
print(data.shape, data.dtype)
print(data[:5])

(13213, 2670) bool
[[False  True  True ...  True  True  True]
 [ True False  True ...  True  True False]
 [ True  True False ... False False  True]
 [ True  True  True ... False False False]
 [ True False False ...  True False  True]]


In [3]:
syn_data = np.load("syn/medgan_uw_1.npy")
print(syn_data.shape, syn_data.dtype)
print(syn_data[:5])

(19800, 2670) int8
[[1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]]
